# Generated by Django 4.1.6 on 2023-02-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('ActorId', models.AutoField(primary_key=True, serialize=False)),
                ('ActorName', models.CharField(max_length=100)),
                ('ActorDOB', models.DateField(default='2023-01-01')),
                ('ActorMovies', models.IntegerField(default='0')),
                ('MovieLists', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=100)),
                ('MovieDescription', models.CharField(max_length=1000)),
                ('MovieReleaseDate', models.DateField(default='2023-01-01')),
                ('MovieUpvotes', models.IntegerField()),
                ('MovieDownvotes', models.IntegerField()),
                ('MovieActors', models.IntegerField(default='0')),
                ('ActorLists', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.actor')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.movie')),
            ],
        ),
    ]
